baseURL = "http://imihajlow.github.io/"
languageCode = "en-us"
title = "Ivan's blog"
theme = "hugo-bearblog"
enableRobotsTxt = true

[params]
  AuthorName = "Ivan Mikhailov"
  GitHubUser = "imihajlow"
